butelka/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('milk.urls')),
]

milk/urls.py
from django.urls import path
from .views import HomeView, RecordView, RecordViewNon, CheckTotalView, FeedExportView, FoodExportView, DownloadView

app_name = 'milk'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('record/', RecordView.as_view(), name='record'),
    path('recordnon/', RecordViewNon.as_view(), name='recordnon'),
    path('check_total/', CheckTotalView.as_view(), name='check_total'),
    path('food/', FoodExportView.as_view(), name='food'),
    path('feed/', FeedExportView.as_view(), name='feed'),
    path('download/', DownloadView.as_view(), name='download'),
]

milk/models.py
from django.db import models


class Feed(models.Model):
    feeder = models.CharField(blank=True, max_length=1, choices=(('', 'Kto karmił?'), ('M', 'Mama'), ('T', 'Tata'), ('O', 'Ktoś inny')))
    time = models.DateTimeField()
    milk = models.IntegerField()

    def __str__(self):
        return f'Nakarmiona o {self.time:%H}:{self.time:%M} {self.time:%d}-{self.time:%m}-{self.time:%Y} ' \
               f'{self.milk} ml mleka przez {self.feeder}'


class Food(models.Model):
    feeder = models.CharField(blank=True, max_length=1, choices=(('', 'Kto karmił?'), ('M', 'Mama'), ('T', 'Tata'), ('O', 'Ktoś inny')))
    type = models.CharField(blank=True, max_length=50)
    factory = models.CharField(blank=True, max_length=50)
    time = models.DateTimeField()
    foods = models.IntegerField()

    def __str__(self):
        return f'Nakarmiona o {self.time:%H}:{self.time:%M} {self.time:%d}-{self.time:%m}-{self.time:%Y} ' \
               f'{self.foods} g {self.type} marki {self.factory} przez {self.feeder}'

milk/forms.py
from django import forms
from .models import Feed
from .models import Food

class RecordForm(forms.ModelForm):
    class Meta:
        model = Feed
        fields = ['feeder', 'time', 'milk']
        labels = {'feeder': '', 'time': 'Kiedy?', 'milk': 'Ile mililitrów mleka?'}

class RecordNonForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = ['feeder', 'time', 'foods', 'factory', 'type']
        labels = {'feeder': '', 'time': 'Kiedy?', 'foods': 'Ile gramów jedzenia?', 'factory': 'jakiej firmy?', 'type': 'co zjadła? (np. kaszkę albo kurczaczka z ziemniaczkami)'}

milk/views.py
from datetime import datetime
from django.views.generic import TemplateView, CreateView, ListView
from django.urls import reverse_lazy
from django.utils.timezone import now
from datetime import timedelta
from django.db.models import Sum
from .forms import RecordForm
from .models import Feed
from .models import Food
from .forms import RecordNonForm

from excel_response import ExcelView


class FeedExportView(ExcelView):
    timestamp = datetime.now().strftime('%Y%m%d_%H_%M_%S')
    output_filename = 'Feed_{timestamp}'.format(timestamp=timestamp)
    model = Feed


class FoodExportView(ExcelView):
    timestamp = datetime.now().strftime('%Y%m%d_%H_%M_%S')
    output_filename = 'Food_{timestamp}'.format(timestamp=timestamp)
    model = Food


class DownloadView(TemplateView):
    template_name = 'milk/download.html'


class HomeView(TemplateView):

    """General status and available options.

    Time till next planned feeding (3h between feedings over 60 ml of milk)
    Progressbar till next feeding

    Choice of available options.

    - Record feeding
    - Check sum of feedings

    Information about last feeding regardless the quantity of milk

    """

    template_name = 'milk/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        try:
            last_feed = Feed.objects.latest('time')
            last_food = Food.objects.latest('time')
            hungry_seconds = (now() - last_feed.time).total_seconds()
            hungry_hours = int(hungry_seconds / 3600)
            hungry_minutes = int((hungry_seconds % 3600) / 60)
            last_big_feed = Feed.objects.filter(milk__gte=60).latest('time')
            minutes_since_last_big_feed = int((now() - last_big_feed.time).total_seconds() / 60)
            till_next_feed = 360 - minutes_since_last_big_feed
            percent = int(minutes_since_last_big_feed / 3.60)
        except Feed.DoesNotExist:
            last_feed = None
            last_food = None
            hungry_hours = '-'
            hungry_minutes = '-'
            hungry_seconds = 0
            till_next_feed = '-'
            percent = 0

        context['last_feed'] = last_feed
        context['last_food'] = last_food
        context['hungry_hours'] = hungry_hours
        context['hungry_minutes'] = hungry_minutes
        context['hungry_seconds'] = hungry_seconds
        context['minutes'] = till_next_feed
        cap = lambda x: x if x < 100 else 100
        context['bar'] = cap(percent)
        return context


class RecordView(CreateView):

    """Form gathers data about feeding

    - Who was feeding? (optional)
    - When? (automatically filled with current date and time)
    - How much milk? (in milliliters)

    """

    template_name = 'milk/record.html'
    form_class = RecordForm
    success_url = reverse_lazy('milk:home')

    def get_initial(self):
        return {'time': now()}

class RecordViewNon(CreateView):

    """Form gathers data about feeding

    - Who was feeding? (optional)
    - When? (automatically filled with current date and time)
    - How much milk? (in milliliters)

    """

    template_name = 'milk/recordnon.html'
    form_class = RecordNonForm
    success_url = reverse_lazy('milk:home')

    def get_initial(self):
        return {'time': now()}

class CheckTotalView(ListView):

    """Overview report

    - Information about quantity of milk consumed on the current day
    - Information about consumption on previous day
    - List of recent feedings

    """

    template_name = 'milk/check_total.html'
    queryset = Feed.objects.order_by('-time')[:10]

    def get_context_data(self, **kwargs):
        context = super(CheckTotalView, self).get_context_data(**kwargs)
        context['feed_total'] = Feed.objects.filter(time__date=now().today()).aggregate(Sum('milk'))
        context['feed_yesterday'] = Feed.objects.filter(time__date=now().today() - timedelta(days=1)
                                                        ).aggregate(Sum('milk'))
        context['other_food'] = Food.objects.order_by('-time')[:10]
        context['food_yesterday'] = Food.objects.filter(time__date=now().today() - timedelta(days=1)
                                                        ).aggregate(Sum('foods'))

        context['food_total'] = Food.objects.filter(time__date=now().today()).aggregate(Sum('foods'))

        print(context)
        return context

milk/templates/milk/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0">
  <title>Butelka</title>
  {% load static %}
  {% include 'material/includes/material_css.html' %}
  <script src="{% static 'material/js/jquery.js' %}"></script>
  {% include 'material/includes/material_js.html' %}
</head>
<body class="valign-wrapper2">
<div class="container expand-on-small-only">
  {% block body_block %}
  {% endblock %}
</div>
</body>
</html>

milk/templates/milk/check_total.html
{% extends 'milk/base.html' %}
{% block body_block %}
  <div class="row valign change-form">
    <div class="col s12 m8 offset-m2 l8 offset-l2">
      <div class="card">
        <div class="card-content">

          {% if feed_total.milk__sum and food_total.foods__sum %}
            <h4>Dzisiaj zjadła już {{ feed_total.milk__sum }} ml mleka oraz {{ food_total.foods__sum }} g innych
              rzeczy.</h4>
          {% elif feed_total.milk__sum and not food_total.foods__sum %}
            <h4>Dzisiaj zjadła już {{ feed_total.milk__sum }} ml mleka ale nie jadła jeszcze niczego innego</h4>
          {% elif not feed_total.milk__sum and food_total.foods__sum %}
            <h4>Dzisiaj zjadła już {{ food_total.foods__sum }} g jedzenia ale nie jadła jeszcze mleka </h4>
          {% elif not feed_total.milk__sum and not food_total.foods__sum %}
            <h5>Jeszcze dziś nie jadła</h5>
          {% endif %}

          {% if feed_yesterday.milk__sum and food_yesterday.foods__sum %}
            <h5>Wczoraj zjadła {{ feed_yesterday.milk__sum }} ml mleka i {{ food_yesterday.foods__sum }} g innych
              rzeczy.</h5>
          {% elif feed_yesterday.milk__sum and not food_yesterday.foods__sum %}
            <h5>Wczoraj zjadła {{ feed_yesterday.milk__sum }} ml mleka ale nie jadła innych rzeczy.</h5>

          {% elif not feed_yesterday.milk__sum and not food_yesterday.foods__sum %}
            <h5>Nie jadła wczoraj</h5>
          {% endif %}

          <h6>Ostatnie mleko:</h6>

          <ul>
            {% for feed in object_list %}
              <li>{{ feed.milk }} ml {{ feed.time|date:"d-m-Y" }} o {{ feed.time|date:"G:i" }}</li>
            {% endfor %}
          </ul>
          <h6>Inne jedzenie:</h6>
          <ul>
            {% for food in other_food %}
              <li>{{ food.foods }} g {{ food.type }} firmy {{ food.factory }} {{ food.time|date:"d-m-Y" }}
                o {{ food.time|date:"G:i" }}</li>
            {% endfor %}
          </ul>
          <a href="{% url 'milk:home' %}">Powrót</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

milk/templates/milk/download.html
{% extends 'milk/base.html' %}
{% block body_block %}
  <div class="row">
    <a href="{%  url 'milk:feed' %}" class="waves-effect waves-light btn-large">Feed</a>
    <a href="{%  url 'milk:food' %}" class="waves-effect waves-light btn-large">Food</a>
  </div>
{% endblock %}

milk/templates/milk/home.html
{% extends 'milk/base.html' %}
{% block body_block %}
  <div class="row valign change-form">
    <div class="col s12 m8 offset-m2 l8 offset-l2">
      <div class="card">
        <div class="card-content">
          {% if last_feed == None %}
            <p>Nie ma jeszcze informacji o dużych karmieniach (&#8805 60 ml).</p>
          {% else %}
            {% if minutes > 0 %}
              <p>Do sześciu godzin od ostatniego mleka &#8805 60 ml brakuje {{ minutes }} min.</p>
            {% else %}
              <p>Minęło ponad sześć godziny od ostatniego mleka</p>
            {% endif %}
          {% endif %}
          <div class="progress">
            <div class="determinate" style="width: {{ bar }}%"></div>
          </div>
          <h4 id="id_action" class="center-align">Wybierz akcję</h4>
          <div class="row">
            <div class="col s12 m12 l12 center-align" style="margin-bottom: 0px;">
              <a href="{% url 'milk:record' %}">
                <button type="submit" name="_submit" class="btn btn-primary btn-lg" id="id_record">Zapisz mleko</button>

              </a>

            </div>
          </div>
          <div class="row">
            <div class="col s12 m12 l12 center-align" style="margin-bottom: 0px;">
              <a href="{% url 'milk:recordnon' %}">
                <button type="submit" name="_submit" class="btn btn-primary btn-lg" id="id_record_food">Zapisz inne
                  jedzenie
                </button>
              </a>
            </div>
          </div>
          <div class="row">
            <div class="col s12 m12 l12 center-align" style="margin-bottom: 0px;">
              <a href="{% url 'milk:check_total' %}">
                <button type="submit" name="_submit" class="btn btn-primary btn-lg" id="id_check_total">Sprawdź ile już
                  dziś zjadła
                </button>
              </a>
            </div>
          </div>
          {% if hungry_hours != 0 %}
            <h5>Od ostatniego karmienia minęło {{ hungry_hours }} godz. {{ hungry_minutes }} min.</h5>
          {% else %}
            <h5>Od ostatniego karmienia minęło {{ hungry_minutes }} min.</h5>
          {% endif %}
          <h5>Ostatni raz jadła {{ last_feed.time|date:"d-m-Y" }} o {{ last_feed.time|date:"G:i" }}</h5>
          <h5>Zjadła {{ last_feed.milk }} ml</h5>
          <h5>Ostatnio zjadła też {{ last_food.foods }} g {{ last_food.type }} firmy {{ last_food.factory }}
            o {{ last_food.time|date:"G:i" }}</h5>
        </div>
        <div class="row">
          <div class="col s12 m12 l12 center-align" style="margin-bottom: 0px;">
            <a href="{% url 'milk:download' %}" class="waves-effect waves-light btn-large">Download</a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

milk/templates/milk/record.html
{% extends 'milk/base.html' %}
{% block body_block %}
  {% load material_form %}
  <div class="row valign change-form">
    <div class="col s12 m8 offset-m2 l8 offset-l2">
      <div class="card">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card-content">
            <h2>{% form form=form %}</h2>
            <h2>{% endform %}</h2>
            <button type="submit" name="_submit" class="btn btn-primary btn-lg">Zapisz</button>
            <br><br><a href="{% url 'milk:home' %}">Powrót</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

milk/templates/milk/recordnon.html
{% extends 'milk/base.html' %}
{% block body_block %}
  {% load material_form %}
  <div class="row valign change-form">
    <div class="col s12 m8 offset-m2 l8 offset-l2">
      <div class="card">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card-content">
            {% form form=form %}
            {% endform %}
            <button type="submit" name="_submit" class="btn btn-primary btn-lg">Zapisz</button>
            <br><br><a href="{% url 'milk:home' %}">Powrót</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}